language: python
sudo: yes
dist: xenial

services:
  - docker

env:
  global:
    - IMAGE_NAME=dhsncats/dmarc-import
    - DOCKER_USER=jsf9k
    - secure: "tokvtXaT0X6EWsoG3WnJMsDQFRw2IkU3gKDKiCdKWOv4LpSvbuTAvZ4y7eyiDRo1l4PmOZjOW8fIKc0k8xLzPsw0jPhe0ILngwUytSnKmLNkavEreQPb7gGwLAyuO9T35fwNa5KjwYNeRwRenyGOLCBeaEeipsyaek6YXSOKzjeAcUHOcHy/J7BQKJYEaLGFq7iTXmor51pBhZW+1BPeYXbS7dpYrPf99vtIkaZgAbHPzPHY9NHKw2ATLar6fSRi+IZe3ppl9tzh4rIWy5USOA2qIwe81jONbRf6xnTBwEMY6mXOVu3W22/uM7ldmMT2ocFNeZewbUix/FjVO3HxsEz6dMiD2iFb2DCXIaQBKVxdQtx7aKSm4VBCLEf8N1LbuqLSiF3xnFvKAR1+h3htajeX11Lh2iWIqwCSqKMul0jNy1vfbPI4rwP7G1guWb5EHgL76RFkQLm7DFtt6ybqsPn0fD0rf9/1C95hC4dwuAaOL4ZsTF7voy5cgEoXHymhsAKDACFdIHl1GYqrELFoCkKKhuh83nkNDI9hbiqTnOXv8rmMOuRBEr0IgJzHGISi4vZulW2ms/7+AnSdBUL/A/jEkk2k1ef6adhFolyUzrJWfIL80Bu6bTSASaDn98qlT7ulOR9UWiqBK7OyZhFmsde9PzNYGVCEwCXIruqZ7x0="

python:
  - '3.6'

before_install:
  - sudo apt-get install -y shellcheck

install:
  - pip install flake8 pytest-cov coveralls
  - pip install -e .

script:
  - shellcheck bump_version.sh tag.sh
  - flake8 .
#  - pytest --cov=dmarc
  - docker-compose config --quiet
  - travis_scripts/build_docker_image.sh

after_success:
  - coveralls

deploy:
  - provider: pypi
    user: jsf9k
    password:
      secure: "ZYlXA94D/FGRpxZ6jHq7ZEYBN92NmCe3QuM2j1Yr3MhAeFnt3V0KnV1IQwxEu2S9znW293AnBxNwORon5MHtnP0seyybuReYFu//6n3q5M+gU5qIIwAKAqqXfIKwsolcrwQmoKiiKS5RAS047e+6oxREUGKUPLLTxJ8qLvuBdT6EFp+3qrlocu/nTXJq4Lz/F+utDk+dc7GVoZU4EroeN2a/eNRf0YCOaY4DIpkbD0AHdwgPENvxrZ1M7A2Qz6/jlqNdyUWLVbLKHTCPPDaOHYrN+8gYTio4mgqIifPtoTkhL6/eWSwUiiKumgOmxrIJwdkpmA15LNISz7XicXqhIZ2vW4hi/el92iBkWMH4lmNIrmJOOUbuNEiKf128vUR4DM4f87nqU67yEyRl+Q6CNv+INEgkt6G699q9AIoRbQVMsHdrjv+kffSMFxpEbT5qRRWylNmh23SPOVoEug6VMTlKuVJ46AV4n2nowE4Tv8HfCTSFQeRY6gwUXCUVo56xUPKsoVE1WZeAyJTxHS8oVr7CJmiWvMhSUo40tYwu5G3/zUYDVYHWTjN2WXf3/IFNArKioDxtI2X590Qmy83eKuiiizl0dUWPl/tqnSTw1836CbeflEjns1RBWQVv+52m/JmGtYnjP/v7zKMw9tMm8fcjEoyJdODmaNXPUqVcX6E="
    distributions: sdist bdist_wheel
    on:
      tags: true
      python: '3.6'
  - provider: script
    script: travis_scripts/deploy_to_docker_hub.sh
    on:
      tags: true
      python: '3.6'
