language: python

sudo: false

python:
  - '3.4'
  - '3.5'
  - '3.6'

install:
  - pip install -e .[test]
  - pip install flake8
  - pip install pytest-cov coveralls

script:
  - pytest --cov=dmarc
  - flake8 .

after_success:
  - coveralls
