version: '3.1'

secrets:
  aws_creds:
    file: secrets/aws/credentials
  aws_config:
    file: secrets/aws/config
  dmarcian_token:
    file: secrets/dmarcian/token

services:
  dmarc-importer:
    build:
      context: .
    image: dhsncats/dmarc-importer:latest
    # command: --schema=/usr/src/boat/dmarc/rua_mod.xsd --s3-bucket=cyhy-dmarc-report-emails --s3-keys=000pphml9c59uumftg3tppllld51e0c07u110bg1 --domains=d.txt --log-level=debug
    command: --schema=/usr/src/boat/dmarc/rua_mod.xsd --s3-bucket=cyhy-dmarc-report-emails --s3-keys=000pphml9c59uumftg3tppllld51e0c07u110bg1 --log-level=debug --elasticsearch=blahblah --es-index=blah --dmarcian-token=/run/secrets/dmarcian_token
    secrets:
      - aws_creds
      - aws_config
      - dmarcian_token
    environment:
      - AWS_CONFIG_FILE=/run/secrets/aws_config
      - AWS_SHARED_CREDENTIALS_FILE=/run/secrets/aws_creds
      - AWS_PROFILE=default
